In [ ]:
import os

In [ ]:
!pip install ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.3/721.3 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 62.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 61.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 53.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import datetime
import shutil
from pathlib import Path
from collections import Counter

import yaml
import numpy as np
import pandas as pd
from ultralytics import YOLO
from sklearn.model_selection import KFold

In [ ]:
import cv2
import torch

In [ ]:
dataset_path = Path('/content/gdrive/My Drive/ES100root') # replace with 'path/to/dataset' for your custom data
labels = sorted(dataset_path.rglob("labels_s/*.txt")) # all data in 'labels'

In [ ]:
yaml_file = '/content/gdrive/My Drive/ES100root/config.yaml'  # your data YAML with data directories and names dictionary
with open(yaml_file, 'r', encoding="utf8") as y:
    classes = yaml.safe_load(y)
    classes = classes['names']
cls_idx = sorted(classes)

In [ ]:
indx = [l.stem for l in labels] # uses base filename as ID (no extension)
labels_df = pd.DataFrame([], columns=cls_idx, index=indx)

In [ ]:
for label in labels:
    lbl_counter = Counter()
    print(label)

    with open(label,'r') as lf:
        lines = lf.readlines()

    for l in lines:
        # classes for YOLO label uses integer at first position of each line
        lbl_counter[int(l.split(' ')[0])] += 1

    labels_df.loc[label.stem] = lbl_counter[0]

labels_df = labels_df.fillna(0.0) # replace `nan` values with `0.0`

/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000000.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000001.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000002.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000003.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000004.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000005.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000006.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000007.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000008.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000009.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000010.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000011.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000012.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000013.txt
/content/gdrive/My Drive/ES100root/labels_s/P1_frame_000014.txt
/content/gdrive/My Drive/ES100root/label

In [ ]:
ksplit = 5
kf = KFold(n_splits=ksplit, shuffle=True, random_state=20)   # setting random_state for repeatable results

kfolds = list(kf.split(labels_df))

In [ ]:
folds = [f'split_{n}' for n in range(1, ksplit + 1)]
folds_df = pd.DataFrame(index=indx, columns=folds)

for idx, (train, val) in enumerate(kfolds, start=1):
    folds_df[f'split_{idx}'].loc[labels_df.iloc[train].index] = 'train'
    folds_df[f'split_{idx}'].loc[labels_df.iloc[val].index] = 'val'

In [ ]:
fold_lbl_distrb = pd.DataFrame(index=folds, columns=cls_idx)

for n, (train_indices, val_indices) in enumerate(kfolds, start=1):
    train_totals = labels_df.iloc[train_indices].sum()
    val_totals = labels_df.iloc[val_indices].sum()

    # To avoid division by zero, we add a small value (1E-7) to the denominator
    ratio = val_totals / (train_totals + 1E-7)
    fold_lbl_distrb.loc[f'split_{n}'] = ratio

In [ ]:
supported_extensions = ['.jpg', '.jpeg', '.png']

# Initialize an empty list to store image file paths
images = []

# Loop through supported extensions and gather image files
for ext in supported_extensions:
    images.extend(sorted((dataset_path / 'images' / 'train').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'images' / 'val').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'image_temp' / 'train_temp').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'image_temp' / 'val_temp').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'labels_temp' / 'P8_images').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'image_temp' / 'P1').rglob(f"*{ext}")))

# Create the necessary directories and dataset YAML files (unchanged)
save_path = Path(dataset_path / f'{datetime.date.today().isoformat()}_{ksplit}-Fold_Cross-val-134589')
save_path.mkdir(parents=True, exist_ok=True)
ds_yamls = []

for split in folds_df.columns:
    # Create directories
    split_dir = save_path / split
    split_dir.mkdir(parents=True, exist_ok=True)
    (split_dir / 'train' / 'images').mkdir(parents=True, exist_ok=True)
    (split_dir / 'train' / 'labels').mkdir(parents=True, exist_ok=True)
    (split_dir / 'val' / 'images').mkdir(parents=True, exist_ok=True)
    (split_dir / 'val' / 'labels').mkdir(parents=True, exist_ok=True)

    # Create dataset YAML files
    dataset_yaml = split_dir / f'{split}_dataset.yaml'
    ds_yamls.append(dataset_yaml)

    with open(dataset_yaml, 'w') as ds_y:
        yaml.safe_dump({
            'path': split_dir.as_posix(),
            'train': 'train',
            'val': 'val',
            'names': classes
        }, ds_y)

In [ ]:
sorted_image = sorted(images, key = lambda image: image.stem)

In [ ]:
label_counter = 0
for image in sorted_image:
  if image.stem in folds_df.index:
    for split, k_split in folds_df.loc[image.stem].items():
        # Destination directory
        img_to_path = save_path / split / k_split / 'images'
        lbl_to_path = save_path / split / k_split / 'labels'

        # Copy image and label files to new directory (SamefileError if file already exists)
        shutil.copy(image, img_to_path / image.name)
        shutil.copy(labels[label_counter], lbl_to_path / labels[label_counter].name)
    print(f"Image inputted from '{image.name}' and label inputted from '{labels[label_counter].name}'.")
    label_counter += 1

Image inputted from 'P1_frame_000000.png' and label inputted from 'P1_frame_000000.txt'.
Image inputted from 'P1_frame_000001.png' and label inputted from 'P1_frame_000001.txt'.
Image inputted from 'P1_frame_000002.png' and label inputted from 'P1_frame_000002.txt'.
Image inputted from 'P1_frame_000003.png' and label inputted from 'P1_frame_000003.txt'.
Image inputted from 'P1_frame_000004.png' and label inputted from 'P1_frame_000004.txt'.
Image inputted from 'P1_frame_000005.png' and label inputted from 'P1_frame_000005.txt'.
Image inputted from 'P1_frame_000006.png' and label inputted from 'P1_frame_000006.txt'.
Image inputted from 'P1_frame_000007.png' and label inputted from 'P1_frame_000007.txt'.
Image inputted from 'P1_frame_000008.png' and label inputted from 'P1_frame_000008.txt'.
Image inputted from 'P1_frame_000009.png' and label inputted from 'P1_frame_000009.txt'.
Image inputted from 'P1_frame_000010.png' and label inputted from 'P1_frame_000010.txt'.
Image inputted from '

In [ ]:
save_path_background = Path(dataset_path / f'{datetime.date.today().isoformat()}_{ksplit}-Fold_Cross-val-backgrounds')
save_path_background.mkdir(parents=True, exist_ok=True)

for image in sorted_image:
  if image.stem not in folds_df.index:

    shutil.copy(image, save_path_background / image.name)
    print(f"Image '{image.name}' not in folds_df.")

Image 'P1_frame_000043.png' not in folds_df.
Image 'P1_frame_000044.png' not in folds_df.
Image 'P1_frame_000045.png' not in folds_df.
Image 'P1_frame_000128.png' not in folds_df.
Image 'P3_frame_000000.png' not in folds_df.
Image 'P3_frame_000001.png' not in folds_df.
Image 'P3_frame_000038.png' not in folds_df.
Image 'P3_frame_000039.png' not in folds_df.
Image 'P3_frame_000040.png' not in folds_df.
Image 'P3_frame_000047.png' not in folds_df.
Image 'P3_frame_000049.png' not in folds_df.
Image 'P3_frame_000052.png' not in folds_df.
Image 'P3_frame_000080.png' not in folds_df.
Image 'P3_frame_000081.png' not in folds_df.
Image 'P3_frame_000082.png' not in folds_df.
Image 'P3_frame_000083.png' not in folds_df.
Image 'P3_frame_000084.png' not in folds_df.
Image 'P3_frame_000085.png' not in folds_df.
Image 'P3_frame_000086.png' not in folds_df.
Image 'P3_frame_000087.png' not in folds_df.
Image 'P3_frame_000088.png' not in folds_df.
Image 'P3_frame_000089.png' not in folds_df.
Image 'P3_

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

!scp -r /content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-backgrounds '/content/gdrive/My Drive/ES100root/'

cp: '/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-backgrounds' and '/content/gdrive/My Drive/ES100root/2024-03-19_5-Fold_Cross-val-backgrounds' are the same file


In [ ]:
model = YOLO('yolov8s-seg.pt', task = 'detect')

100%|██████████| 22.8M/22.8M [00:00<00:00, 316MB/s]


In [ ]:
ds_yamls_temp = ['/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/split_1_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/split_2_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/split_3_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/split_4_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/split_5_dataset.yaml']

In [ ]:
results = {}

ksplit = 5

# Define your additional arguments here
batch = 16
project = 'kfold_demo'
epochs = 10

for k in range(ksplit):
    dataset_yaml = ds_yamls_temp[k]
    model.train(data=dataset_yaml, cfg = '/content/best_hyperparameters-2.yaml', epochs=epochs, batch=batch, project=project, optimizer = 'AdamW')  # include any train arguments
    results[k] = model.metrics  # save output metrics for further analysis

Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/split_1_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save

100%|██████████| 755k/755k [00:00<00:00, 39.8MB/s]


Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics

100%|██████████| 6.23M/6.23M [00:00<00:00, 191MB/s]


AMP: checks passed ✅


train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/train/labels... 1052 images, 88 backgrounds, 0 corrupt: 100%|██████████| 1140/1140 [00:18<00:00, 62.69it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/val/labels... 264 images, 22 backgrounds, 0 corrupt: 100%|██████████| 286/286 [00:05<00:00, 55.84it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_1/val/labels.cache
Plotting labels to kfold_demo/train/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      4.75G      2.216      3.236      5.259      1.845          4        640: 100%|██████████| 72/72 [00:25<00:00,  2.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.69it/s]

                   all        286        277          0          0          0          0          0          0          0          0



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      4.88G      1.968      2.346      1.381      1.697          4        640: 100%|██████████| 72/72 [00:18<00:00,  3.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.22it/s]

                   all        286        277     0.0981      0.307     0.0675     0.0275      0.102      0.318     0.0661     0.0285



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      4.87G      1.859      2.127      1.246      1.643          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.43it/s]

                   all        286        277      0.118      0.213     0.0786     0.0338      0.116      0.209     0.0747     0.0336



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      4.86G      1.755      1.975      1.118      1.565          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.72it/s]

                   all        286        277      0.834      0.769      0.845      0.462      0.837      0.773      0.848      0.523



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      4.86G      1.694       1.92      1.003      1.492          5        640: 100%|██████████| 72/72 [00:18<00:00,  3.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.48it/s]

                   all        286        277      0.454      0.412      0.303      0.127      0.542      0.491      0.459       0.25



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      4.87G      1.623       1.83     0.9269      1.455          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.94it/s]

                   all        286        277      0.929      0.859      0.916      0.567      0.929      0.859      0.917      0.595



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      4.86G      1.558      1.732      0.854      1.414          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.15it/s]

                   all        286        277      0.891      0.816      0.909      0.571      0.885      0.816      0.907       0.61



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      4.86G      1.484      1.701     0.8334      1.362          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.50it/s]

                   all        286        277       0.91      0.918      0.955      0.608      0.907      0.914      0.956      0.646



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      4.86G      1.431      1.588     0.7656      1.316          3        640: 100%|██████████| 72/72 [00:19<00:00,  3.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.58it/s]

                   all        286        277      0.951      0.931      0.969      0.643      0.951      0.931      0.972       0.66



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      4.87G      1.336      1.557     0.7025      1.281          4        640: 100%|██████████| 72/72 [00:20<00:00,  3.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.77it/s]

                   all        286        277       0.97      0.934      0.965      0.637      0.966       0.93      0.967      0.675



10 epochs completed in 0.073 hours.
Optimizer stripped from kfold_demo/train/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train/weights/best.pt, 23.8MB

Validating kfold_demo/train/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.01it/s]


                   all        286        277       0.97      0.934      0.965      0.637      0.966       0.93      0.967      0.675
Speed: 0.1ms preprocess, 1.1ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to kfold_demo/train
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/split_2_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train2, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False,

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/train/labels... 1053 images, 88 backgrounds, 0 corrupt: 100%|██████████| 1141/1141 [00:16<00:00, 68.04it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/val/labels... 263 images, 22 backgrounds, 0 corrupt: 100%|██████████| 285/285 [00:05<00:00, 53.57it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_2/val/labels.cache
Plotting labels to kfold_demo/train2/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train2
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      5.39G      1.496      1.753     0.8381      1.362          5        640: 100%|██████████| 72/72 [00:25<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.71it/s]

                   all        285        274      0.769      0.752      0.824      0.503      0.778      0.759      0.832      0.532



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      5.46G      1.605      1.883     0.9342      1.431          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.06it/s]

                   all        285        274      0.884      0.825      0.902      0.506      0.877      0.832      0.912      0.534



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      5.45G      1.572      1.795      0.881      1.425          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.39it/s]

                   all        285        274      0.848      0.858      0.894      0.524      0.848      0.857      0.893      0.557



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      5.47G      1.572      1.796     0.8696      1.413          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.60it/s]

                   all        285        274      0.914      0.843      0.917      0.539      0.927      0.836      0.919        0.6



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      5.41G      1.539      1.736     0.8258      1.396          7        640: 100%|██████████| 72/72 [00:20<00:00,  3.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.59it/s]

                   all        285        274      0.959      0.863      0.929      0.579      0.964       0.88      0.943      0.611



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      5.47G      1.408      1.597     0.7506       1.33          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.34it/s]

                   all        285        274      0.946      0.894      0.957      0.624       0.95      0.898      0.958      0.648



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      5.41G      1.393      1.566     0.7445        1.3          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.46it/s]

                   all        285        274      0.968      0.891      0.959      0.622      0.964      0.888      0.955      0.654



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      5.46G      1.353      1.545      0.672      1.272          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.65it/s]

                   all        285        274      0.943      0.931      0.961      0.644      0.945       0.92      0.961      0.669



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      5.46G       1.33      1.512     0.6479       1.26          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.62it/s]

                   all        285        274      0.951      0.927      0.966      0.653      0.959      0.933      0.972      0.681



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10       5.4G      1.263      1.458     0.6033      1.228          4        640: 100%|██████████| 72/72 [00:19<00:00,  3.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.42it/s]

                   all        285        274       0.97       0.96      0.979       0.67      0.967       0.96      0.979      0.706



10 epochs completed in 0.074 hours.
Optimizer stripped from kfold_demo/train2/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train2/weights/best.pt, 23.8MB

Validating kfold_demo/train2/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.92it/s]


                   all        285        274       0.97       0.96      0.979       0.67      0.967       0.96      0.979      0.707
Speed: 0.1ms preprocess, 1.2ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to kfold_demo/train2
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/split_3_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train3, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/train/labels... 1053 images, 88 backgrounds, 0 corrupt: 100%|██████████| 1141/1141 [00:17<00:00, 64.57it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/val/labels... 263 images, 22 backgrounds, 0 corrupt: 100%|██████████| 285/285 [00:05<00:00, 51.87it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_3/val/labels.cache
Plotting labels to kfold_demo/train3/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train3
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10         6G      1.362      1.549     0.6979      1.278          5        640: 100%|██████████| 72/72 [00:24<00:00,  2.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.88it/s]

                   all        285        283      0.894      0.831      0.902      0.557      0.894      0.831      0.906       0.57



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      6.08G      1.442      1.627     0.7628       1.34          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.41it/s]

                   all        285        283      0.926      0.927      0.967      0.618      0.926      0.927      0.961      0.618



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      6.06G       1.39       1.59     0.7382      1.303          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.50it/s]

                   all        285        283      0.931      0.905      0.959      0.603      0.931      0.905      0.956      0.619



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      6.08G      1.365      1.579     0.7149      1.271          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.55it/s]

                   all        285        283      0.955      0.895      0.967      0.619      0.955      0.895      0.967      0.624



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      6.02G      1.396      1.555     0.7181      1.293          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.58it/s]

                   all        285        283      0.948      0.896      0.968      0.637      0.951      0.901      0.964      0.657



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      6.07G      1.343      1.535     0.6767      1.264          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.76it/s]

                   all        285        283      0.966      0.908      0.974      0.636      0.966      0.908      0.971      0.647



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      6.07G      1.296      1.526     0.6564       1.25          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.24it/s]

                   all        285        283      0.898      0.905       0.95      0.621      0.895      0.915      0.948       0.64



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      6.08G      1.263      1.416     0.6248      1.221          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.51it/s]

                   all        285        283      0.938      0.951      0.973      0.661      0.944       0.94       0.97      0.646



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      6.07G      1.232      1.383     0.5864      1.204          4        640: 100%|██████████| 72/72 [00:20<00:00,  3.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.40it/s]

                   all        285        283      0.959      0.929      0.981      0.666      0.959      0.929      0.981      0.676



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      6.08G      1.194      1.351     0.5651      1.197          4        640: 100%|██████████| 72/72 [00:20<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.52it/s]

                   all        285        283      0.951      0.936      0.981      0.683      0.951      0.936      0.981      0.685



10 epochs completed in 0.075 hours.
Optimizer stripped from kfold_demo/train3/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train3/weights/best.pt, 23.8MB

Validating kfold_demo/train3/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.04it/s]


                   all        285        283       0.95      0.936      0.981      0.683       0.95      0.936      0.981      0.686
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to kfold_demo/train3
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/split_4_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train4, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/train/labels... 1053 images, 88 backgrounds, 0 corrupt: 100%|██████████| 1141/1141 [00:19<00:00, 58.47it/s]


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/val/labels... 263 images, 22 backgrounds, 0 corrupt: 100%|██████████| 285/285 [00:05<00:00, 48.78it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_4/val/labels.cache
Plotting labels to kfold_demo/train4/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train4
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      6.61G      1.256       1.44     0.6155      1.212          6        640: 100%|██████████| 72/72 [00:25<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.62it/s]

                   all        285        276       0.95      0.956      0.985      0.654      0.946      0.952       0.98      0.671



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      6.68G      1.319      1.473     0.6589       1.26          5        640: 100%|██████████| 72/72 [00:21<00:00,  3.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        285        276      0.951      0.957      0.984      0.667      0.954       0.96      0.985       0.68



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      6.68G      1.346      1.484     0.7064      1.271          4        640: 100%|██████████| 72/72 [00:20<00:00,  3.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.60it/s]

                   all        285        276      0.944      0.942      0.971      0.625      0.951      0.949      0.981      0.655



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      6.68G      1.333      1.492     0.6683      1.244          4        640: 100%|██████████| 72/72 [00:21<00:00,  3.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.54it/s]

                   all        285        276      0.869      0.914      0.936      0.614      0.869      0.935      0.948      0.644



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      6.63G      1.287      1.475     0.6401      1.216          7        640: 100%|██████████| 72/72 [00:20<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.18it/s]

                   all        285        276       0.94      0.903      0.966      0.659      0.943      0.907       0.97      0.668



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      6.69G      1.238      1.405     0.6101       1.21          5        640: 100%|██████████| 72/72 [00:21<00:00,  3.36it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.03it/s]

                   all        285        276      0.975       0.96      0.984      0.691      0.976      0.967       0.99      0.704



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      6.69G      1.209      1.397     0.5965       1.19          6        640: 100%|██████████| 72/72 [00:19<00:00,  3.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.62it/s]

                   all        285        276      0.938       0.96      0.979      0.665      0.938       0.96      0.979      0.698



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      6.68G      1.207      1.358     0.5788      1.186          4        640: 100%|██████████| 72/72 [00:20<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.25it/s]

                   all        285        276      0.974      0.957      0.988      0.714      0.971      0.958      0.983      0.706



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      6.68G      1.148      1.363     0.5499      1.162          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.54it/s]

                   all        285        276      0.964      0.968      0.989      0.706      0.964      0.968      0.989      0.723



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      6.66G      1.137      1.316     0.5366      1.148          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.62it/s]

                   all        285        276      0.971      0.968      0.987      0.711      0.962      0.978      0.988      0.695



10 epochs completed in 0.076 hours.
Optimizer stripped from kfold_demo/train4/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train4/weights/best.pt, 23.8MB

Validating kfold_demo/train4/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.56it/s]


                   all        285        276      0.964      0.969      0.989      0.705      0.964      0.969      0.989      0.723
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to kfold_demo/train4
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/split_5_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train5, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/train/labels... 1053 images, 88 backgrounds, 0 corrupt: 100%|██████████| 1141/1141 [00:18<00:00, 61.39it/s]


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/val/labels... 263 images, 22 backgrounds, 0 corrupt: 100%|██████████| 285/285 [00:05<00:00, 49.53it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-19_5-Fold_Cross-val-134589/split_5/val/labels.cache
Plotting labels to kfold_demo/train5/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train5
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      7.19G      1.249      1.386     0.6057      1.216          6        640: 100%|██████████| 72/72 [00:27<00:00,  2.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  1.98it/s]

                   all        285        282      0.951      0.883      0.968      0.688      0.947      0.879      0.966      0.688



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      7.28G      1.248       1.43     0.6074      1.204          4        640: 100%|██████████| 72/72 [00:21<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.58it/s]

                   all        285        282      0.943      0.943      0.971      0.649      0.947      0.945      0.977      0.658



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      7.28G      1.292      1.422      0.627      1.229          4        640: 100%|██████████| 72/72 [00:22<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:05<00:00,  1.77it/s]

                   all        285        282      0.615      0.702      0.759      0.528      0.615      0.702      0.761      0.544



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      7.29G      1.256      1.403     0.6597      1.229          4        640: 100%|██████████| 72/72 [00:21<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.73it/s]

                   all        285        282      0.978      0.933      0.976      0.698      0.978      0.933      0.978      0.709



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      7.28G      1.253      1.392     0.6217      1.216          6        640: 100%|██████████| 72/72 [00:20<00:00,  3.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.71it/s]

                   all        285        282      0.966      0.933      0.981      0.688      0.971      0.929      0.979      0.696



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      7.29G      1.231      1.382     0.5911      1.204          5        640: 100%|██████████| 72/72 [00:23<00:00,  3.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.66it/s]

                   all        285        282      0.961      0.965      0.983      0.696      0.955      0.972      0.984      0.701



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      7.26G      1.224      1.373     0.5972      1.201          5        640: 100%|██████████| 72/72 [00:19<00:00,  3.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.46it/s]

                   all        285        282      0.952      0.926      0.965      0.657      0.924      0.944      0.963      0.666



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      7.26G      1.195      1.339     0.5596       1.18          5        640: 100%|██████████| 72/72 [00:21<00:00,  3.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.63it/s]

                   all        285        282      0.954      0.961      0.979      0.715      0.965       0.95      0.981      0.725



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      7.29G      1.141      1.301     0.5223      1.156          5        640: 100%|██████████| 72/72 [00:20<00:00,  3.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:04<00:00,  2.16it/s]

                   all        285        282      0.958      0.972      0.982      0.718      0.961      0.972      0.984      0.708



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      7.28G      1.117      1.295      0.498      1.136          5        640: 100%|██████████| 72/72 [00:21<00:00,  3.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:03<00:00,  2.29it/s]

                   all        285        282      0.964      0.972      0.984      0.733      0.964      0.972      0.984      0.728



10 epochs completed in 0.079 hours.
Optimizer stripped from kfold_demo/train5/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train5/weights/best.pt, 23.8MB

Validating kfold_demo/train5/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 9/9 [00:07<00:00,  1.18it/s]


                   all        285        282      0.964      0.972      0.984      0.733      0.964      0.972      0.984      0.728
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 1.6ms postprocess per image
Results saved to kfold_demo/train5


In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

!scp -r /content/kfold_demo_134589 '/content/gdrive/My Drive/ES100root/runs'

In [ ]:
models_split1_134589 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134589/train/weights/best.pt')
models_split2_134589 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134589/train2/weights/best.pt')
models_split3_134589 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134589/train3/weights/best.pt')
models_split4_134589 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134589/train4/weights/best.pt')
models_split5_134589 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134589/train5/weights/best.pt')

In [ ]:
sources = ['/content/gdrive/My Drive/ES100root/Videos/CDW_4.6.23_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/CDW_11.16.22_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/CFY_6.6.22_RUL_PA1_1fps.mp4',
           '/content/gdrive/My Drive/ES100root/Videos/CFY_6.13.22_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/LS_5.15.23_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4',
           '/content/gdrive/My Drive/ES100root/Videos/US_2.15.23_RUL_PA1_1fps.mp4']

patient_num = ['1','3','4','5','7','8','9']
patient_counter = 0
for source in sources:
  results_split1_134589 = models_split1_134589(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_134589", name="split1")  # generator of Results objects
  results_split2_134589 = models_split2_134589(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_134589", name="split2")
  results_split3_134589 = models_split3_134589(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_134589", name="split3")
  results_split4_134589 = models_split4_134589(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_134589", name="split4")
  results_split5_134589 = models_split5_134589(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_134589", name="split5")

  counter = 0
  for r in results_split1_134589:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_134589/split1_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split2_134589:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_134589/split2_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split3_134589:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_134589/split3_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split4_134589:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_134589/split4_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split5_134589:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_134589/split5_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1


  patient_counter += 1

Streaming output truncated to the last 5000 lines.
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0., 0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0., 0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0., 0., 0.], device='cuda:0')
clss
tensor([0., 0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device