In [ ]:
import os

In [ ]:
!pip install ultralytics

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 723.1/723.1 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 42.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 51.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 62.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 30.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 12.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import datetime
import shutil
from pathlib import Path
from collections import Counter

import yaml
import numpy as np
import pandas as pd
from ultralytics import YOLO
from sklearn.model_selection import KFold

In [ ]:
import cv2

In [ ]:
import torch

In [ ]:
list_input_dir = ['/content/gdrive/My Drive/ES100root/masks','/content/gdrive/My Drive/ES100root/masks_patient/P5','/content/gdrive/My Drive/ES100root/masks_patient/P7', '/content/gdrive/My Drive/ES100root/masks_patient/P8', '/content/gdrive/My Drive/ES100root/masks_patient/P9' ]
outdir= '/content/gdrive/My Drive/ES100_Kfold/labels'

In [ ]:
for indir in list_input_dir:
  for j in os.listdir(indir):
      image_path = os.path.join(indir, j)
      # load the binary mask and get its contours
      if "frame" in image_path:
        mask = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        _, mask = cv2.threshold(mask, 1, 255, cv2.THRESH_BINARY)
        print(image_path)

        H, W = mask.shape
        contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # convert the contours to polygons
        polygons = []
        for cnt in contours:
            if cv2.contourArea(cnt) > 200:
                polygon = []
                for point in cnt:
                    x, y = point[0]
                    polygon.append(x / W)
                    polygon.append(y / H)
                polygons.append(polygon)
        with open('{}.txt'.format(os.path.join(outdir, j)[:-4]), 'w') as f:
          for polygon in polygons:
              for p_, p in enumerate(polygon):
                  if p_ == len(polygon) - 1:
                      f.write('{}\n'.format(p))
                  elif p_ == 0:
                      f.write('0 {} '.format(p))
                  else:
                      f.write('{} '.format(p))

          f.close()

/content/gdrive/My Drive/ES100root/masks/P1_frame_000002.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000005.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000003.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000004.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000000.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000006.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000001.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000016.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000009.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000010.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000008.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000007.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000015.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000011.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000013.png
/content/gdrive/My Drive/ES100root/masks/P1_frame_000014.png
/content/gdrive/My Drive

In [ ]:
dataset_path = Path('/content/gdrive/My Drive/ES100root') # replace with 'path/to/dataset' for your custom data
labels = sorted(dataset_path.rglob("labels_s/*.txt")) # all data in 'labels'

In [ ]:
backgrounds = sorted(dataset_path.rglob("2024-03-18_5-Fold_Cross-val-backgrounds/*.png"))

In [ ]:
indx_back = [back.stem for back in backgrounds] # uses base filename as ID (no extension)
back_df = pd.DataFrame([], columns=cls_idx, index=indx_back)

In [ ]:


kfolds_back = list(kf.split(back_df))

In [ ]:
folds = [f'split_{n}' for n in range(1, ksplit + 1)]
folds_df_back = pd.DataFrame(index=indx_back, columns=folds)

for idx, (train, val) in enumerate(kfolds, start=1):
    folds_df[f'split_{idx}'].loc[back_df.iloc[train].index] = 'train'
    folds_df[f'split_{idx}'].loc[back_df.iloc[val].index] = 'val'

IndexError: positional indexers are out-of-bounds

In [ ]:
yaml_file = '/content/gdrive/My Drive/ES100root/config.yaml'  # your data YAML with data directories and names dictionary
with open(yaml_file, 'r', encoding="utf8") as y:
    classes = yaml.safe_load(y)
    classes = classes['names']
cls_idx = sorted(classes)


In [ ]:
indx = [l.stem for l in labels] # uses base filename as ID (no extension)
labels_df = pd.DataFrame([], columns=cls_idx, index=indx)

In [ ]:
labels_df

posterior ascending
P3_frame_000002                 NaN
P3_frame_000003                 NaN
P3_frame_000004                 NaN
P3_frame_000005                 NaN
P3_frame_000006                 NaN
...                             ...
P9_frame_000216                 NaN
P9_frame_000217                 NaN
P9_frame_000218                 NaN
P9_frame_000219                 NaN
P9_frame_000220                 NaN

[1153 rows x 1 columns]

In [ ]:
for label in labels:
    lbl_counter = Counter()
    print(label)

    with open(label,'r') as lf:
        lines = lf.readlines()

    for l in lines:
        # classes for YOLO label uses integer at first position of each line
        lbl_counter[int(l.split(' ')[0])] += 1

    labels_df.loc[label.stem] = lbl_counter[0]

labels_df = labels_df.fillna(0.0) # replace `nan` values with `0.0`

/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000002.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000003.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000004.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000005.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000006.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000007.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000008.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000009.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000010.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000011.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000012.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000013.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000014.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000015.txt
/content/gdrive/My Drive/ES100root/labels_s/P3_frame_000016.txt
/content/gdrive/My Drive/ES100root/label

K-FOLD DATASET SPLIT

In [ ]:
ksplit = 5
kf = KFold(n_splits=ksplit, shuffle=True, random_state=20)   # setting random_state for repeatable results

kfolds = list(kf.split(labels_df))

In [ ]:
folds = [f'split_{n}' for n in range(1, ksplit + 1)]
folds_df = pd.DataFrame(index=indx, columns=folds)

for idx, (train, val) in enumerate(kfolds, start=1):
    folds_df[f'split_{idx}'].loc[labels_df.iloc[train].index] = 'train'
    folds_df[f'split_{idx}'].loc[labels_df.iloc[val].index] = 'val'

In [ ]:
fold_lbl_distrb = pd.DataFrame(index=folds, columns=cls_idx)

for n, (train_indices, val_indices) in enumerate(kfolds, start=1):
    train_totals = labels_df.iloc[train_indices].sum()
    val_totals = labels_df.iloc[val_indices].sum()

    # To avoid division by zero, we add a small value (1E-7) to the denominator
    ratio = val_totals / (train_totals + 1E-7)
    fold_lbl_distrb.loc[f'split_{n}'] = ratio

In [ ]:
supported_extensions = ['.jpg', '.jpeg', '.png']

# Initialize an empty list to store image file paths
images = []

# Loop through supported extensions and gather image files
for ext in supported_extensions:
    images.extend(sorted((dataset_path / 'images' / 'train').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'images' / 'val').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'image_temp' / 'train_temp').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'image_temp' / 'val_temp').rglob(f"*{ext}")))
    images.extend(sorted((dataset_path / 'labels_temp' / 'P8_images').rglob(f"*{ext}")))

# Create the necessary directories and dataset YAML files (unchanged)
save_path = Path(dataset_path / f'{datetime.date.today().isoformat()}_{ksplit}-Fold_Cross-val')
save_path.mkdir(parents=True, exist_ok=True)
ds_yamls = []

for split in folds_df.columns:
    # Create directories
    split_dir = save_path / split
    split_dir.mkdir(parents=True, exist_ok=True)
    (split_dir / 'train' / 'images').mkdir(parents=True, exist_ok=True)
    (split_dir / 'train' / 'labels').mkdir(parents=True, exist_ok=True)
    (split_dir / 'val' / 'images').mkdir(parents=True, exist_ok=True)
    (split_dir / 'val' / 'labels').mkdir(parents=True, exist_ok=True)

    # Create dataset YAML files
    dataset_yaml = split_dir / f'{split}_dataset.yaml'
    ds_yamls.append(dataset_yaml)

    with open(dataset_yaml, 'w') as ds_y:
        yaml.safe_dump({
            'path': split_dir.as_posix(),
            'train': 'train',
            'val': 'val',
            'names': classes
        }, ds_y)

In [ ]:
sorted_image = sorted(images, key = lambda image: image.stem)

In [ ]:
sorted_image

[PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000000.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000001.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000002.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000003.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000004.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000005.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000006.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000007.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000008.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000009.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000010.png'),
 PosixPath('/content/gdrive/My Drive/ES100root/images/train/P3_frame_000011.png'),
 Pos

In [ ]:
label.stem

'P9_frame_000220'

In [ ]:
label_counter = 0
for image in sorted_image:
  if image.stem in folds_df.index:
    for split, k_split in folds_df.loc[image.stem].items():
        # Destination directory
        img_to_path = save_path / split / k_split / 'images'
        lbl_to_path = save_path / split / k_split / 'labels'

        # Copy image and label files to new directory (SamefileError if file already exists)
        shutil.copy(image, img_to_path / image.name)
        shutil.copy(labels[label_counter], lbl_to_path / labels[label_counter].name)
    print(f"Image inputted from '{image.name}' and label inputted from '{labels[label_counter].name}'.")
    label_counter += 1

Image inputted from 'P3_frame_000002.png' and label inputted from 'P3_frame_000002.txt'.
Image inputted from 'P3_frame_000003.png' and label inputted from 'P3_frame_000003.txt'.
Image inputted from 'P3_frame_000004.png' and label inputted from 'P3_frame_000004.txt'.
Image inputted from 'P3_frame_000005.png' and label inputted from 'P3_frame_000005.txt'.
Image inputted from 'P3_frame_000006.png' and label inputted from 'P3_frame_000006.txt'.
Image inputted from 'P3_frame_000007.png' and label inputted from 'P3_frame_000007.txt'.
Image inputted from 'P3_frame_000008.png' and label inputted from 'P3_frame_000008.txt'.
Image inputted from 'P3_frame_000009.png' and label inputted from 'P3_frame_000009.txt'.
Image inputted from 'P3_frame_000010.png' and label inputted from 'P3_frame_000010.txt'.
Image inputted from 'P3_frame_000011.png' and label inputted from 'P3_frame_000011.txt'.
Image inputted from 'P3_frame_000012.png' and label inputted from 'P3_frame_000012.txt'.
Image inputted from '

In [ ]:
save_path_background

PosixPath('/content/gdrive/My Drive/ES100root/2024-03-18_5-Fold_Cross-val-backgrounds')

In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

!scp -r /content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val-backgrounds '/content/gdrive/My Drive/ES100root/'

cp: '/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val-backgrounds' and '/content/gdrive/My Drive/ES100root/2024-03-18_5-Fold_Cross-val-backgrounds' are the same file


In [ ]:
save_path_background = Path(dataset_path / f'{datetime.date.today().isoformat()}_{ksplit}-Fold_Cross-val-backgrounds')
save_path_background.mkdir(parents=True, exist_ok=True)

for image in sorted_image:
  if image.stem not in folds_df.index:

    shutil.copy(image, save_path_background / image.name)
    print(f"Image '{image.name}' not in folds_df.")

Image 'P3_frame_000000.png' not in folds_df.
Image 'P3_frame_000001.png' not in folds_df.
Image 'P3_frame_000038.png' not in folds_df.
Image 'P3_frame_000039.png' not in folds_df.
Image 'P3_frame_000040.png' not in folds_df.
Image 'P3_frame_000047.png' not in folds_df.
Image 'P3_frame_000049.png' not in folds_df.
Image 'P3_frame_000052.png' not in folds_df.
Image 'P3_frame_000080.png' not in folds_df.
Image 'P3_frame_000081.png' not in folds_df.
Image 'P3_frame_000082.png' not in folds_df.
Image 'P3_frame_000083.png' not in folds_df.
Image 'P3_frame_000084.png' not in folds_df.
Image 'P3_frame_000085.png' not in folds_df.
Image 'P3_frame_000086.png' not in folds_df.
Image 'P3_frame_000087.png' not in folds_df.
Image 'P3_frame_000088.png' not in folds_df.
Image 'P3_frame_000089.png' not in folds_df.
Image 'P3_frame_000090.png' not in folds_df.
Image 'P3_frame_000091.png' not in folds_df.
Image 'P3_frame_000092.png' not in folds_df.
Image 'P3_frame_000093.png' not in folds_df.
Image 'P3_

Training YOLO with K-fold data spilts

In [ ]:
#weights_path = '/content/gdrive/My Drive/ES100root/runs/EXP1_134579/exp1_A100/exp1m_final/weights/best.pt'
model = YOLO('yolov8s-seg.pt', task = 'detect')

100%|██████████| 22.8M/22.8M [00:00<00:00, 311MB/s]


In [ ]:
ds_yamls_temp = ['/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_1/split_1_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_2/split_2_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_3/split_3_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_4/split_4_dataset.yaml',
                 '/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_5/split_5_dataset.yaml']

In [ ]:
import torch.optim as optim

# Define hyperparameters

# Instantiate optimizer with specified hyperparameters
optimizer = optim.AdamW(model.parameters(), lr0=0.00734, lrf=0.00605, momentum=0.97106, weight_decay = 0.00055, warmup_epochs = 3.06711, warmup_momentum =0.72107, box = 8.39131, cls = 0.49205,dfl=1.67383,hsv_h=0.01125,hsv_s=0.4879,hsv_v=0.4,degrees=0.0,translate=0.10116,scale=0.58559,shear=0,perspective=0,flipud=0,fliplr=0.54761,mosaic=1,mixup=0,copy_paste=0)

TypeError: AdamW.__init__() got an unexpected keyword argument 'lr0'

In [ ]:
import torch.optim as optim

In [ ]:
results = {}

ksplit = 5

# Define your additional arguments here
batch = 16
project = 'kfold_demo'
epochs = 10

for k in range(ksplit):
    dataset_yaml = ds_yamls_temp[k]
    model.train(data=dataset_yaml, cfg = '/content/best_hyperparameters-2.yaml', epochs=epochs, batch=batch, project=project, optimizer = 'AdamW')  # include any train arguments
    results[k] = model.metrics  # save output metrics for further analysis

Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_1/split_1_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train4, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=F

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_1/train/labels.cache... 922 images, 68 backgrounds, 0 corrupt: 100%|██████████| 990/990 [00:00<?, ?it/s]


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 239, in _feed
    reader_close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 177, in close
    self._close()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor
val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_1/val/labels.cache... 231 images, 17 backgrounds, 0 corrupt: 100%|██████████| 248/248 [00:00<?, ?it/s]


Plotting labels to kfold_demo/train4/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train4
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10       8.9G      2.168      2.993       3.17      1.922         14        640: 100%|██████████| 62/62 [00:25<00:00,  2.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.07it/s]

                   all        248        257   0.000309     0.0856   0.000165   4.53e-05          0          0          0          0



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      8.75G      2.153       2.61      1.549      2.044         16        640: 100%|██████████| 62/62 [00:17<00:00,  3.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.15it/s]

                   all        248        257     0.0704     0.0467     0.0173    0.00472     0.0212     0.0233     0.0042    0.00103



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      8.75G      1.959      2.344      1.408      1.929         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.36it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.44it/s]

                   all        248        257      0.183       0.35      0.238        0.1      0.179      0.342      0.229      0.116



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      8.61G      1.869      2.185       1.21      1.825         14        640: 100%|██████████| 62/62 [00:16<00:00,  3.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.45it/s]

                   all        248        257      0.641      0.447      0.526       0.26      0.666      0.447      0.539      0.282



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      8.62G      1.798      2.093       1.11      1.795         15        640: 100%|██████████| 62/62 [00:18<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.36it/s]

                   all        248        257      0.751      0.584      0.699      0.356      0.755      0.588      0.701      0.396



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      8.63G      1.682      1.924      1.061      1.722         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]

                   all        248        257      0.774      0.665       0.78      0.416      0.769      0.661      0.776      0.449



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      8.62G      1.612      1.856     0.9349      1.666         18        640: 100%|██████████| 62/62 [00:18<00:00,  3.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.32it/s]

                   all        248        257       0.88      0.782      0.885      0.498      0.887       0.79      0.897      0.542



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      8.62G      1.537      1.804     0.9129      1.595         13        640: 100%|██████████| 62/62 [00:17<00:00,  3.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.42it/s]

                   all        248        257      0.852      0.829      0.898      0.509      0.845       0.85      0.904      0.556



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      8.62G      1.499      1.701     0.8361      1.573         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.92it/s]

                   all        248        257      0.861      0.819      0.896      0.534      0.868      0.821      0.898      0.563



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      8.62G      1.454      1.667     0.8057      1.508         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.30it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.60it/s]

                   all        248        257      0.932      0.852      0.921      0.575      0.932      0.858       0.93      0.629



10 epochs completed in 0.073 hours.
Optimizer stripped from kfold_demo/train4/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train4/weights/best.pt, 23.8MB

Validating kfold_demo/train4/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.82it/s]


                   all        248        257      0.935      0.852      0.921      0.576      0.932      0.856       0.93      0.629
Speed: 0.1ms preprocess, 1.1ms inference, 0.0ms loss, 1.2ms postprocess per image
Results saved to kfold_demo/train4
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_2/split_2_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train5, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_2/train/labels... 922 images, 68 backgrounds, 0 corrupt: 100%|██████████| 990/990 [00:16<00:00, 61.86it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_2/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_2/val/labels... 231 images, 17 backgrounds, 0 corrupt: 100%|██████████| 248/248 [00:04<00:00, 54.41it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_2/val/labels.cache
Plotting labels to kfold_demo/train5/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train5
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      8.96G      1.607      1.846     0.9165      1.633         11        640: 100%|██████████| 62/62 [00:24<00:00,  2.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.86it/s]

                   all        248        245      0.898      0.771      0.876      0.512      0.898      0.792      0.881      0.534



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      9.05G      1.627      1.873     0.9655      1.642         16        640: 100%|██████████| 62/62 [00:20<00:00,  3.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.52it/s]

                   all        248        245      0.754      0.739      0.786      0.432      0.758      0.743      0.801      0.484



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      9.09G      1.607      1.877     0.9336       1.63         14        640: 100%|██████████| 62/62 [00:19<00:00,  3.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.12it/s]

                   all        248        245      0.898       0.83        0.9      0.533      0.903      0.834      0.899      0.555



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      9.09G      1.531       1.77     0.8515      1.568         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.26it/s]

                   all        248        245      0.864      0.828      0.894      0.497      0.864      0.826      0.896      0.545



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      9.09G      1.534      1.742     0.8381      1.574         17        640: 100%|██████████| 62/62 [00:19<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.43it/s]

                   all        248        245      0.896       0.82      0.908      0.529      0.883      0.808      0.897      0.536



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      9.08G      1.475      1.713     0.8045      1.545         12        640: 100%|██████████| 62/62 [00:24<00:00,  2.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  3.24it/s]

                   all        248        245      0.884      0.853      0.917      0.572      0.877      0.857      0.914      0.573



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      9.09G       1.47      1.645     0.7468      1.519         18        640: 100%|██████████| 62/62 [00:17<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.20it/s]

                   all        248        245      0.931      0.898      0.944      0.588      0.924      0.894      0.944      0.636



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      9.09G      1.393      1.599     0.7204      1.464         14        640: 100%|██████████| 62/62 [00:19<00:00,  3.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.29it/s]

                   all        248        245      0.897      0.922      0.957      0.618      0.897      0.922      0.959      0.652



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      9.09G      1.351      1.499     0.6777      1.447         14        640: 100%|██████████| 62/62 [00:17<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.55it/s]

                   all        248        245      0.939      0.882      0.953      0.622      0.922      0.865      0.943       0.63



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      9.09G      1.304      1.461     0.6463      1.408         14        640: 100%|██████████| 62/62 [00:19<00:00,  3.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]

                   all        248        245      0.966      0.943      0.978      0.647      0.953      0.931      0.968      0.668



10 epochs completed in 0.074 hours.
Optimizer stripped from kfold_demo/train5/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train5/weights/best.pt, 23.8MB

Validating kfold_demo/train5/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:06<00:00,  1.17it/s]


                   all        248        245      0.966      0.943      0.978      0.648      0.954      0.931      0.968      0.669
Speed: 0.2ms preprocess, 1.7ms inference, 0.0ms loss, 3.9ms postprocess per image
Results saved to kfold_demo/train5
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_3/split_3_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train6, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_3/train/labels... 922 images, 68 backgrounds, 0 corrupt: 100%|██████████| 990/990 [00:17<00:00, 55.09it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_3/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_3/val/labels... 231 images, 17 backgrounds, 0 corrupt: 100%|██████████| 248/248 [00:04<00:00, 50.32it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_3/val/labels.cache
Plotting labels to kfold_demo/train6/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train6
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      9.63G      1.468      1.673     0.7274      1.544         14        640: 100%|██████████| 62/62 [00:26<00:00,  2.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.56it/s]

                   all        248        246       0.91      0.858      0.937      0.577      0.921      0.841      0.925      0.589



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      9.73G      1.514      1.672     0.7917      1.569         16        640: 100%|██████████| 62/62 [00:18<00:00,  3.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.23it/s]

                   all        248        246       0.92      0.902      0.948      0.623       0.92      0.902      0.953      0.627



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      9.71G       1.49      1.691     0.8074      1.546         13        640: 100%|██████████| 62/62 [00:17<00:00,  3.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.29it/s]

                   all        248        246      0.908       0.88      0.943       0.57      0.917      0.898      0.955      0.605



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      9.68G      1.542      1.659     0.8151      1.575         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.30it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  2.69it/s]

                   all        248        246      0.929      0.931      0.966      0.627      0.925      0.927      0.962      0.628



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      9.74G      1.465      1.669     0.7736      1.527         14        640: 100%|██████████| 62/62 [00:17<00:00,  3.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.18it/s]

                   all        248        246      0.911      0.902      0.964      0.577      0.911      0.902      0.964      0.631



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      9.71G      1.439      1.573      0.776      1.521         12        640: 100%|██████████| 62/62 [00:17<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.51it/s]

                   all        248        246      0.897      0.888      0.949       0.63      0.895      0.886      0.945      0.615



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10       9.7G      1.426      1.558     0.7222      1.487         15        640: 100%|██████████| 62/62 [00:20<00:00,  3.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.27it/s]

                   all        248        246      0.974      0.909      0.978      0.653      0.974      0.909      0.982      0.664



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      9.74G      1.351       1.49     0.6717      1.438         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  2.80it/s]

                   all        248        246      0.961      0.939      0.983      0.661      0.961      0.939      0.978      0.687



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      9.69G      1.302      1.445     0.6155      1.426         14        640: 100%|██████████| 62/62 [00:19<00:00,  3.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.26it/s]

                   all        248        246      0.971      0.931      0.986      0.686      0.959      0.944      0.987      0.688



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10       9.7G      1.268      1.402     0.6117      1.364         14        640: 100%|██████████| 62/62 [00:18<00:00,  3.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  2.77it/s]

                   all        248        246       0.96      0.966      0.989      0.683       0.97      0.967      0.989      0.676



10 epochs completed in 0.072 hours.
Optimizer stripped from kfold_demo/train6/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train6/weights/best.pt, 23.8MB

Validating kfold_demo/train6/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:08<00:00,  1.05s/it]


                   all        248        246       0.97      0.931      0.986      0.686      0.959      0.944      0.987      0.687
Speed: 0.1ms preprocess, 2.1ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to kfold_demo/train6
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_4/split_4_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train7, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_4/train/labels... 923 images, 68 backgrounds, 0 corrupt: 100%|██████████| 991/991 [00:16<00:00, 59.40it/s] 


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_4/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_4/val/labels... 230 images, 17 backgrounds, 0 corrupt: 100%|██████████| 247/247 [00:05<00:00, 43.04it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_4/val/labels.cache
Plotting labels to kfold_demo/train7/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train7
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10      10.3G      1.352      1.558     0.6618      1.472         15        640: 100%|██████████| 62/62 [00:29<00:00,  2.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.52it/s]

                   all        247        252      0.944      0.944      0.976      0.645      0.937      0.941      0.974      0.629



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10      10.4G      1.428      1.605     0.7121      1.509         16        640: 100%|██████████| 62/62 [00:25<00:00,  2.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.54it/s]

                   all        247        252      0.928       0.92      0.965      0.622      0.928       0.92      0.959       0.65



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10      10.3G      1.382      1.642     0.7133      1.487         16        640: 100%|██████████| 62/62 [00:22<00:00,  2.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.38it/s]

                   all        247        252      0.928      0.914      0.967      0.609      0.928      0.914      0.966      0.632



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10      10.4G      1.382      1.542     0.7195      1.493         15        640: 100%|██████████| 62/62 [00:22<00:00,  2.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.61it/s]

                   all        247        252      0.963      0.941      0.978      0.622      0.963      0.933      0.972      0.646



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      10.4G      1.359      1.533     0.6793      1.473         16        640: 100%|██████████| 62/62 [00:20<00:00,  2.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.47it/s]

                   all        247        252      0.988      0.947      0.981      0.639       0.97      0.933      0.972      0.631



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10      10.4G      1.321      1.509     0.6562       1.44         15        640: 100%|██████████| 62/62 [00:18<00:00,  3.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.23it/s]

                   all        247        252      0.954      0.933      0.974      0.624      0.934      0.961      0.974      0.657



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10      10.4G      1.312      1.448     0.6512      1.445         15        640: 100%|██████████| 62/62 [00:24<00:00,  2.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.77it/s]

                   all        247        252      0.953      0.955      0.983      0.663      0.953      0.955      0.982      0.671



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10      10.4G      1.277       1.44     0.6214      1.424         16        640: 100%|██████████| 62/62 [00:23<00:00,  2.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  2.96it/s]

                   all        247        252      0.974      0.944      0.989      0.651      0.971      0.937      0.983      0.647



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10      10.4G      1.233      1.393     0.5914      1.375         13        640: 100%|██████████| 62/62 [00:18<00:00,  3.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.66it/s]

                   all        247        252      0.979      0.944      0.989      0.679      0.979      0.944       0.99      0.684



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10      10.4G      1.179      1.373     0.5684      1.334         14        640: 100%|██████████| 62/62 [00:21<00:00,  2.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.43it/s]

                   all        247        252       0.98       0.95      0.991      0.689      0.965      0.971      0.991       0.67



10 epochs completed in 0.084 hours.
Optimizer stripped from kfold_demo/train7/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train7/weights/best.pt, 23.8MB

Validating kfold_demo/train7/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:07<00:00,  1.06it/s]


                   all        247        252      0.979      0.944      0.989      0.679      0.979      0.944       0.99      0.684
Speed: 0.2ms preprocess, 1.7ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to kfold_demo/train7
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
engine/trainer: task=segment, mode=train, model=None, data=/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val/split_5/split_5_dataset.yaml, epochs=10, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=kfold_demo, name=train8, exist_ok=False, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=

train: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_5/train/labels... 923 images, 68 backgrounds, 0 corrupt: 100%|██████████| 991/991 [00:17<00:00, 56.67it/s]


train: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_5/train/labels.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_5/val/labels... 230 images, 17 backgrounds, 0 corrupt: 100%|██████████| 247/247 [00:05<00:00, 46.89it/s]


val: New cache created: /content/gdrive/.shortcut-targets-by-id/1DgH6NEok81EWCSfsITjAjTQzQIDNN6z_/ES100root/2024-03-18_5-Fold_Cross-val/split_5/val/labels.cache
Plotting labels to kfold_demo/train8/labels.jpg... 
optimizer: AdamW(lr=0.00734, momentum=0.97106) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.00055), 76 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to kfold_demo/train8
Starting training for 10 epochs...
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       1/10        11G      1.358      1.498     0.6486      1.457         15        640: 100%|██████████| 62/62 [00:28<00:00,  2.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.22it/s]

                   all        247        244      0.936      0.902      0.964      0.654      0.933       0.91       0.97      0.657



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       2/10        11G      1.335      1.521     0.6706      1.451         12        640: 100%|██████████| 62/62 [00:22<00:00,  2.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.89it/s]

                   all        247        244      0.967      0.922      0.981      0.675      0.939      0.949      0.982      0.673



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       3/10        11G       1.36      1.547     0.6957      1.468         15        640: 100%|██████████| 62/62 [00:22<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.85it/s]

                   all        247        244      0.979      0.937      0.974      0.643      0.979      0.937      0.975      0.654



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       4/10        11G      1.383      1.576     0.7002      1.444         15        640: 100%|██████████| 62/62 [00:23<00:00,  2.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.47it/s]

                   all        247        244      0.939      0.922      0.975      0.668      0.941      0.922      0.976      0.662



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       5/10      11.1G      1.337      1.527     0.6388       1.44         17        640: 100%|██████████| 62/62 [00:24<00:00,  2.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.69it/s]

                   all        247        244       0.95      0.934      0.977      0.656       0.95      0.934      0.977      0.673



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       6/10        11G      1.293      1.498     0.6285      1.397         16        640: 100%|██████████| 62/62 [00:22<00:00,  2.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.72it/s]

                   all        247        244      0.959      0.957      0.987      0.699      0.959      0.957      0.984        0.7



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       7/10        11G      1.298      1.422     0.6109      1.411         15        640: 100%|██████████| 62/62 [00:24<00:00,  2.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.58it/s]

                   all        247        244      0.955      0.967      0.987      0.695      0.955      0.966      0.987      0.697



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       8/10        11G       1.27      1.403     0.5935      1.387         16        640: 100%|██████████| 62/62 [00:24<00:00,  2.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.42it/s]

                   all        247        244      0.988       0.93      0.989      0.724      0.975      0.947      0.989      0.728



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


       9/10        11G      1.201      1.353     0.5582      1.353         13        640: 100%|██████████| 62/62 [00:26<00:00,  2.36it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:05<00:00,  1.57it/s]

                   all        247        244      0.968      0.951      0.987       0.71      0.959      0.963      0.988      0.715



      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size


      10/10        11G      1.184      1.376     0.5316      1.318         14        640: 100%|██████████| 62/62 [00:17<00:00,  3.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.16it/s]

                   all        247        244      0.958      0.971       0.99       0.74      0.971      0.973       0.99      0.719



10 epochs completed in 0.088 hours.
Optimizer stripped from kfold_demo/train8/weights/last.pt, 23.8MB
Optimizer stripped from kfold_demo/train8/weights/best.pt, 23.8MB

Validating kfold_demo/train8/weights/best.pt...
Ultralytics YOLOv8.1.29 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16151MiB)
YOLOv8s-seg summary (fused): 195 layers, 11779987 parameters, 0 gradients, 42.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:04<00:00,  1.79it/s]


                   all        247        244      0.956      0.972       0.99       0.74      0.971      0.971       0.99      0.719
Speed: 0.3ms preprocess, 1.4ms inference, 0.0ms loss, 3.5ms postprocess per image
Results saved to kfold_demo/train8


In [ ]:
import locale
locale.getpreferredencoding = lambda: "UTF-8"

!scp -r /content/kfold_demo_345789 '/content/gdrive/My Drive/ES100root/runs'

In [ ]:
folds_df.to_csv('fold_distribution', sep=',', index=True, encoding='utf-8')

In [ ]:
folds_df

split_1 split_2 split_3 split_4 split_5
P1_frame_000000   train   train   train     val   train
P1_frame_000001     val   train   train   train   train
P1_frame_000002   train   train   train     val   train
P1_frame_000003   train   train     val   train   train
P1_frame_000004   train   train   train   train     val
...                 ...     ...     ...     ...     ...
P9_frame_000216     val   train   train   train   train
P9_frame_000217   train   train     val   train   train
P9_frame_000218   train   train     val   train   train
P9_frame_000219   train   train   train     val   train
P9_frame_000220   train   train   train   train     val

[1173 rows x 5 columns]

In [ ]:
model_1m_split1 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_small/train/weights/best.pt')

source = '/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4'

results_1m_split1 = model_1m(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/", name="exp2m_split1")

counter = 0
for r in results_1m_split1:
  if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]


      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      written = cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/exp2m_iou_split1/P8_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())
      print(written)
  counter += 1



WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 3 posterior ascendings, 14.2ms
video 1/1 (frame 2/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 1 posterior ascending, 12.9ms
video 1/1 (frame 3/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 (no detections), 9.6ms
video 1/1 (frame 4/301) /content/gdrive/My Drive/ES100root/Vide

In [ ]:
model_1m_split3 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134579/train222/weights/best.pt')

source = '/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4'

results_1m_split3 = model_1m(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/", name="exp2m_split3")

counter = 0
for r in results_1m_split3:
  if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]


      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      written = cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/exp2m_iou_split3/P8_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())
      print(written)
  counter += 1



WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 3 posterior ascendings, 15.0ms
video 1/1 (frame 2/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 1 posterior ascending, 10.3ms
video 1/1 (frame 3/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 (no detections), 13.8ms
video 1/1 (frame 4/301) /content/gdrive/My Drive/ES100root/Vid

In [ ]:
model_1m_split4= YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134579/train222/weights/best.pt')

source = '/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4'

results_1m_split4 = model_1m(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/", name="exp2m_split4")

counter = 0
for r in results_1m_split4:
  if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/exp2m_iou_split4/P8_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

  counter += 1



WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 3 posterior ascendings, 10.4ms
video 1/1 (frame 2/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 1 posterior ascending, 10.0ms
video 1/1 (frame 3/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 (no detections), 9.7ms
video 1/1 (frame 4/301) /content/gdrive/My Drive/ES100root/Vide

In [ ]:
model_1m_split5= YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134579/train2222/weights/best.pt')

source = '/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4'

results_1m_split5= model_1m(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/", name="exp2m_split5")

counter = 0
for r in results_1m_split5:
  if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      written = cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/exp2m_iou_split5/P8_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())
      print(written)
  counter += 1



WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 3 posterior ascendings, 13.9ms
video 1/1 (frame 2/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 1 posterior ascending, 10.3ms
video 1/1 (frame 3/301) /content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4: 384x640 (no detections), 9.9ms
video 1/1 (frame 4/301) /content/gdrive/My Drive/ES100root/Vide

In [ ]:
counter = 0
for r in results_1m:
  if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      written = cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/exp2m_iou/P8_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())
      print(written)

  counter += 1

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [ ]:
net = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_134579/train2/weights/best.pt')

model_state_dict = net.state_dict()

torch.save(model_state_dict, 'split2_onlyweights.pt')


In [ ]:
from torchsummary import summary

In [ ]:
model1.info(detailed=True)

layer                                     name  gradient   parameters                shape         mu      sigma
    0                      model.0.conv.weight     False         1296        [48, 3, 3, 3]   -0.00157      0.119 torch.float32
    1                        model.0.bn.weight     False           48                 [48]       3.17      0.738 torch.float32
    2                          model.0.bn.bias     False           48                 [48]      0.173       2.04 torch.float32
    3                      model.1.conv.weight     False        41472       [96, 48, 3, 3]  -0.000604      0.025 torch.float32
    4                        model.1.bn.weight     False           96                 [96]       2.72      0.664 torch.float32
    5                          model.1.bn.bias     False           96                 [96]      0.322       1.13 torch.float32
    6                  model.2.cv1.conv.weight     False         9216       [96, 96, 1, 1]   -0.00371     0.0366 torch.float3

(331, 27285968, 0, 110.64632320000001)

In [ ]:
net.info(detailed=True)

layer                                     name  gradient   parameters                shape         mu      sigma
    0                      model.0.conv.weight     False         1296        [48, 3, 3, 3]  -0.000613       0.12 torch.float32
    1                        model.0.bn.weight     False           48                 [48]       3.15      0.744 torch.float32
    2                          model.0.bn.bias     False           48                 [48]      0.156       2.06 torch.float32
    3                      model.1.conv.weight     False        41472       [96, 48, 3, 3]  -0.000722     0.0297 torch.float32
    4                        model.1.bn.weight     False           96                 [96]       2.71      0.666 torch.float32
    5                          model.1.bn.bias     False           96                 [96]      0.308       1.15 torch.float32
    6                  model.2.cv1.conv.weight     False         9216       [96, 96, 1, 1]   -0.00421     0.0405 torch.float3

/usr/local/lib/python3.10/dist-packages/ultralytics/utils/torch_utils.py:250: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1760.)
  % (i, name, p.requires_grad, p.numel(), list(p.shape), p.mean(), p.std(), p.dtype)


YOLOv8m-seg summary: 331 layers, 27240227 parameters, 0 gradients, 110.4 GFLOPs


(331, 27240227, 0, 110.39150079999999)

In [ ]:
type(model_test)

ultralytics.models.yolo.model.YOLO

In [ ]:
summary('split2_onlyweights.pt',(3,640,640))

AttributeError: 'str' object has no attribute 'apply'

In [ ]:
model1 = YOLO('yolov8m-seg.pt')
model2 = torch.load('split2_onlyweights.pt')

In [ ]:
len(model1.info()['name'])

YOLOv8m-seg summary: 331 layers, 27285968 parameters, 0 gradients, 110.6 GFLOPs


TypeError: tuple indices must be integers or slices, not str

In [ ]:
len(model2.keys())

537

In [ ]:
for keynew, keyorg in zip_directory

In [ ]:
for key, value in zip(model2.keys(), model2.values()):
  print(key + " " + str(len(value)))

model.model.0.conv.weight 48
model.model.0.bn.weight 48
model.model.0.bn.bias 48
model.model.0.bn.running_mean 48
model.model.0.bn.running_var 48


TypeError: len() of a 0-d tensor

In [ ]:
summary(model2,(3,640,640))

AttributeError: 'collections.OrderedDict' object has no attribute 'apply'

In [ ]:
import string
from collections import OrderedDict

In [ ]:
new_dict_keys = OrderedDict()
key_mapping = OrderedDict()


for key in model2.keys():
  key_mapping[key] = key.replace("model.","",1)

for old_key, new_key in key_mapping.items():
    model2[new_key] = model2.pop(old_key)

model2.keys()

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.

In [ ]:
model2_YOLO = YOLO('split2_onlyweights.pt')

KeyError: 'model'

In [ ]:

for param_tensor in model1.state_dict():
  if param_tensor in model2.keys():
    print(model1.state_dict()[param_tensor].size())

torch.Size([48, 3, 3, 3])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([])
torch.Size([96, 48, 3, 3])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([])
torch.Size([96, 96, 1, 1])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([])
torch.Size([96, 192, 1, 1])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([96])
torch.Size([])
torch.Size([48, 48, 3, 3])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([])
torch.Size([48, 48, 3, 3])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([])
torch.Size([48, 48, 3, 3])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([])
torch.Size([48, 48, 3, 3])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([48])
torch.Size([])
torch.Size([192, 96, 3, 3])
torch.Size([192])
torch.Size([192])
torch.Size([192])
torch.Size([192])
torch.Size([])
torch

In [ ]:
model2.i

In [ ]:
new_state_dict = {}
for param_tensor in model2.keys():

    if model1.state_dict()[param_tensor].size() != model2[param_tensor].size():
        new_state_dict[key] = value
    else:
        print(key)

model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2.2.bias
model.model.22.cv4.2

In [ ]:
model1.load_state_dict(new_state_dict)

RuntimeError: Error(s) in loading state_dict for YOLO:
	size mismatch for model.model.22.cv3.0.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.0.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.model.22.cv3.1.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.1.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.model.22.cv3.2.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.2.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).

In [ ]:
model_test = model1

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

if device.type == 'cuda':
    model_test.load_state_dict(model2)
else:
    model_test.load_state_dict(model2)

RuntimeError: Error(s) in loading state_dict for YOLO:
	size mismatch for model.model.22.cv3.0.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.0.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.model.22.cv3.1.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.1.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.model.22.cv3.2.2.weight: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 192, 1, 1]).
	size mismatch for model.model.22.cv3.2.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([80]).

In [ ]:
models_split1_345789 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_345789/train4/weights/best.pt')
models_split2_345789 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_345789/train5/weights/best.pt')
models_split3_345789 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_345789/train6/weights/best.pt')
models_split4_345789 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_345789/train7/weights/best.pt')
models_split5_345789 = YOLO('/content/gdrive/My Drive/ES100root/runs/kfold_demo_345789/train8/weights/best.pt')

In [ ]:
sources = ['/content/gdrive/My Drive/ES100root/Videos/CDW_4.6.23_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/CDW_11.16.22_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/CFY_6.6.22_RUL_PA1_1fps.mp4',
           '/content/gdrive/My Drive/ES100root/Videos/CFY_6.13.22_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/LS_5.15.23_RUL_PA1_1fps.mp4','/content/gdrive/My Drive/ES100root/Videos/LS_5.24.22_RUL_PA1_1fps.mp4',
           '/content/gdrive/My Drive/ES100root/Videos/US_2.15.23_RUL_PA1_1fps.mp4']

patient_num = ['1','3','4','5','7','8','9']
patient_counter = 0
for source in sources:
  results_split1_345789 = models_split1_345789(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_345789", name="split1")  # generator of Results objects
  results_split2_345789 = models_split2_345789(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_345789", name="split2")
  results_split3_345789 = models_split3_345789(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_345789", name="split3")
  results_split4_345789 = models_split4_345789(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_345789", name="split4")
  results_split5_345789 = models_split5_345789(source, save=True, save_conf=True, project="/content/gdrive/My Drive/ES100root/runs/EXP2s_345789", name="split5")

  counter = 0
  for r in results_split1_345789:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_345789/split1_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split2_345789:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_345789/split2_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split3_345789:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_345789/split3_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split4_345789:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_345789/split4_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1

  counter = 0
  for r in results_split5_345789:
    if r.masks != None:
      masks = r.masks.data
      boxes = r.boxes.data

      clss = boxes[:, 5]
      print("clss")
      print(clss)

      seg_classes = list(r.names.values())
      #EXTRACT A SINGLE MASK WITH ALL THE CLASSES
      obj_indices = torch.where(clss != -1)
      obj_masks = masks[obj_indices]
      obj_mask = torch.any(obj_masks, dim=0).int() * 255
      cv2.imwrite(str(f'/content/gdrive/My Drive/ES100root/runs/EXP2s_345789/split5_iou/P{patient_num[patient_counter]}_frame_{counter:06d}.jpg'), obj_mask.cpu().numpy())

    counter += 1


  patient_counter += 1

Streaming output truncated to the last 5000 lines.
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tensor([0.], device='cuda:0')
clss
tens

In [ ]:
model = YOLO('yolov8m-seg.pt')

model.tune(data='/content/gdrive/My Drive/ES100root/2024-03-14_5-Fold_Cross-val/split_5/split_5_dataset.yaml', epochs=10, iterations=100, optimizer='AdamW', plots=True, save=False, val=False)

100%|██████████| 52.4M/52.4M [00:09<00:00, 5.72MB/s]


Tuner: Initialized Tuner instance with 'tune_dir=runs/segment/tune'
Tuner: 💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/100 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
Saved runs/segment/tune/tune_scatter_plots.png
Saved runs/segment/tune/tune_fitness.png

Tuner: 1/100 iterations complete ✅ (249.19s)
Tuner: Results saved to runs/segment/tune
Tuner: Best fitness=1.23144 observed at iteration 1
Tuner: Best fitness metrics are {'metrics/precision(B)': 0.90703, 'metrics/recall(B)': 0.85214, 'metrics/mAP50(B)': 0.91931, 'metrics/mAP50-95(B)': 0.56366, 'metrics/precision(M)': 0.91532, 'metrics/recall

In [ ]:
model = YOLO('yolov8s-seg.pt')

model.tune(data='/content/gdrive/MyDrive/ES100root/2024-03-18_5-Fold_Cross-val-345789/split_3/split_3_dataset.yaml', epochs=10, iterations=30, optimizer='AdamW', plots=False, save=False, val=False)

Tuner: Initialized Tuner instance with 'tune_dir=runs/segment/tune3'
Tuner: 💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/30 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'bgr': 0.0, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
